"""rename address

Revision ID: 932fa2ed3019
Revises: d04119b47633
Create Date: 2023-11-05 20:30:54.940294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932fa2ed3019'
down_revision = 'd04119b47633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
